server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

spring.thymeleaf:
  prefix: classpath:/templates/
  suffix: .html



